# var = 'World'
# print('Hello %s' %var)
# print('Hello {}!'.format(var))
# print(f'Hello {var}!')
# L=list()
# print(bool(L))
# Li=list('0')
# print(bool(Li))
a = int(input())
b = float(input())
c = int(input())
print(format(a, '0=+10d'))
print(format(b, '#>-10.2f'))
print(format(c, '0=19_b'))